const hamburger=document.getElementById('hamburger');const mobileMenu=document.getElementById('mobile-menu');hamburger.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');hamburger.classList.toggle('open');hamburger.setAttribute('aria-expanded',open);mobileMenu.setAttribute('aria-hidden',!open);document.body.style.overflow=open?'hidden':'';});function closeMenu(){mobileMenu.classList.remove('open');hamburger.classList.remove('open');hamburger.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true');document.body.style.overflow='';}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mobileMenu.classList.contains('open'))closeMenu();});function switchCare(t){['basic','active','hourly'].forEach(x=>{document.getElementById('care-'+x).style.display='none';document.getElementById('care-btn-'+x).classList.remove('active');});document.getElementById('care-'+t).style.display='block';document.getElementById('care-btn-'+t).classList.add('active');}
function switchRefresh(t){['one','multi'].forEach(x=>{document.getElementById('refresh-'+x).style.display='none';document.getElementById('refresh-btn-'+x).classList.remove('active');});document.getElementById('refresh-'+t).style.display='block';document.getElementById('refresh-btn-'+t).classList.add('active');}
(function(){function fmt(n){return Math.round(n).toLocaleString('cs-CZ')+'\u00a0Kč';}
function upd(){const h=parseInt(document.getElementById('k-hosting').value),s=parseInt(document.getElementById('k-sprava').value),d=parseInt(document.getElementById('k-domena').value),r=parseInt(document.getElementById('k-roky').value);document.getElementById('k-hosting-out').textContent=fmt(h);document.getElementById('k-sprava-out').textContent=fmt(s);document.getElementById('k-domena-out').textContent=fmt(d);document.getElementById('k-roky-out').textContent=r+(r===1?' rok':r<5?' roky':' let');const ted=(h+s+d)*r,jd=5900+(d*r),us=Math.max(0,ted-jd);document.getElementById('k-ted').textContent=fmt(ted);document.getElementById('k-jd').textContent=fmt(jd);document.getElementById('k-uspora').textContent=fmt(us);const mx=Math.max(ted,jd,1);document.getElementById('k-bar-ted').style.width=Math.round((ted/mx)*100)+'%';document.getElementById('k-bar-jd').style.width=Math.round((jd/mx)*100)+'%';}
['k-hosting','k-sprava','k-domena','k-roky'].forEach(id=>document.getElementById(id).addEventListener('input',upd));upd();})();setTimeout(function(){document.querySelectorAll('.score-num').forEach(function(el){var target=parseInt(el.dataset.target,10);var startTime=performance.now();var dur=1400;function tick(now){var p=Math.min((now-startTime)/dur,1);var ease=1-Math.pow(1-p,3);el.textContent=Math.round(ease*target);if(p<1)requestAnimationFrame(tick);else el.textContent=target;}requestAnimationFrame(tick);});},600);const revealObs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible');});},{threshold:0.08});document.querySelectorAll('.reveal').forEach(el=>revealObs.observe(el));(function(){const track=document.getElementById('refTrack');const prevBtn=document.getElementById('refPrev');const nextBtn=document.getElementById('refNext');if(!track||!prevBtn||!nextBtn)return;let _max=0,_cw=0;function calcMax(){_cw=track.clientWidth;_max=track.scrollWidth-_cw-2;}function update(){prevBtn.disabled=track.scrollLeft<=2;nextBtn.disabled=_max<=2||track.scrollLeft>=_max;}
prevBtn.addEventListener('click',()=>track.scrollBy({left:-_cw,behavior:'smooth'}));nextBtn.addEventListener('click',()=>track.scrollBy({left:_cw,behavior:'smooth'}));track.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',()=>{requestAnimationFrame(()=>{calcMax();update();});});requestAnimationFrame(()=>{calcMax();update();});})();(function(){const el=document.getElementById('scramble-h1');if(!el)return;const orig=el.dataset.value;const chars='01_/X#<>';let raf=null;function scramble(){cancelAnimationFrame(raf);const start=performance.now();const dur=700;function tick(now){const p=Math.min((now-start)/dur,1);const solved=Math.floor(p*orig.length);let out='';for(let i=0;i<orig.length;i++){if(i<solved||orig[i]===' ')out+=orig[i];else out+=chars[Math.floor(Math.random()*chars.length)];}
el.textContent=out;if(p<1)raf=requestAnimationFrame(tick);else el.textContent=orig;}
raf=requestAnimationFrame(tick);}
el.addEventListener('mouseenter',scramble);})();(function(){const form=document.getElementById('contact-form');if(!form)return;const btn=form.querySelector('button[type="submit"]');const btnOrigHTML=btn.innerHTML;form.addEventListener('submit',async function(e){e.preventDefault();const jmeno=form.querySelector('#jmeno').value.trim();const email=form.querySelector('#email').value.trim();const zprava=form.querySelector('#zprava').value.trim();if(!jmeno||!email||!zprava){showMsg('Vyplňte prosím všechna pole.','error');return;}
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){showMsg('Zadejte platnou e-mailovou adresu.','error');return;}
btn.disabled=true;btn.innerHTML='Odesílám… <svg viewBox="0 0 24 24" width="16" height="16" stroke="currentColor" fill="none" stroke-width="2"><circle cx="12" cy="12" r="10" stroke-opacity="0.3"/><path d="M12 2a10 10 0 0 1 10 10" style="animation:spin 0.8s linear infinite;transform-origin:center"/></svg>';try{const data=new FormData(form);const res=await fetch('https://api.web3forms.com/submit',{method:'POST',body:data});const json=await res.json();if(json.success){window.location.href='https://janyskovadigital.cz/podekovani.html';}else{throw new Error(json.message||'Chyba serveru');}}catch(err){showMsg('Něco se pokazilo. Zkuste to znovu nebo mi napište přímo na info@janyskovadigital.cz','error');btn.disabled=false;btn.innerHTML=btnOrigHTML;}});function showMsg(text,type){const old=form.querySelector('.form-msg');if(old)old.remove();const div=document.createElement('div');div.className='form-msg';div.style.cssText='margin-top:12px;padding:12px 18px;border-radius:10px;font-size:14px;'+
(type==='error'?'background:rgba(255,80,80,0.08);border:1px solid rgba(255,80,80,0.25);color:#ff7080;':'background:rgba(0,229,160,0.08);border:1px solid rgba(0,229,160,0.25);color:var(--green);');div.textContent=text;form.appendChild(div);}})();;const mouseGlow=document.querySelector('.mouse-glow');if(mouseGlow)window.addEventListener('mousemove',e=>{mouseGlow.style.setProperty('--mx',e.clientX+'px');mouseGlow.style.setProperty('--my',e.clientY+'px');},{passive:true});window.addEventListener("load",function(){const cnv=document.getElementById("robot-canvas");if(cnv)setTimeout(()=>cnv.style.opacity="0.18",800);function initCanvas(){const canvas=document.getElementById('robot-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');const P='rgba(240,20,122,';let W,H,dpr;let nodes=[],edges=[],pulses=[],t=0;let mouse={x:-9999,y:-9999};let resizeTimer;function resize(){clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){requestAnimationFrame(function(){dpr=window.devicePixelRatio||1;W=window.innerWidth;H=window.innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);build();});},100);}
function build(){nodes=[];edges=[];pulses=[];const count=Math.floor((W*H)/18000);for(let i=0;i<count;i++){const x=Math.random()*W;const y=Math.random()*H;nodes.push({x,y,ox:x,oy:y,vx:0,vy:0,r:1.8+Math.random()*2.2,phase:Math.random()*Math.PI*2,spd:0.3+Math.random()*0.7});}
const maxD=Math.min(W,H)*0.2;nodes.forEach((a,i)=>{nodes.forEach((b,j)=>{if(j<=i)return;const d=Math.hypot(a.x-b.x,a.y-b.y);if(d<maxD&&Math.random()>0.4)edges.push({a,b,maxD});});});for(let i=0;i<12;i++)spawnPulse();}
function spawnPulse(){if(!edges.length)return;const e=edges[Math.floor(Math.random()*edges.length)];pulses.push({a:e.a,b:e.b,t:Math.random()*0.3,spd:0.004+Math.random()*0.008,rev:Math.random()>0.5});}
function frame(){ctx.clearRect(0,0,W,H);t+=0.012;nodes.forEach(n=>{const dx=n.x-mouse.x;const dy=n.y-mouse.y;const dist=Math.hypot(dx,dy);const R=160;if(dist<R&&dist>0){const f=((R-dist)/R)*3.5;n.vx+=(dx/dist)*f;n.vy+=(dy/dist)*f;}
n.vx+=(n.ox-n.x)*0.055;n.vy+=(n.oy-n.y)*0.055;n.vx*=0.82;n.vy*=0.82;n.x+=n.vx;n.y+=n.vy;});edges.forEach(({a,b,maxD})=>{const d=Math.hypot(a.x-b.x,a.y-b.y);if(d>maxD*1.4)return;const alpha=(1-d/(maxD*1.4))*0.18;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=P+alpha+')';ctx.lineWidth=0.6;ctx.stroke();});pulses=pulses.filter(p=>{p.t+=p.spd*(p.rev?-1:1);if(p.t>1.1||p.t<-0.1){spawnPulse();return false;}
const tt=Math.max(0,Math.min(1,p.t));const x=p.a.x+(p.b.x-p.a.x)*tt;const y=p.a.y+(p.b.y-p.a.y)*tt;ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fillStyle=P+'0.7)';ctx.fill();return true;});nodes.forEach(n=>{const pulse=0.5+0.5*Math.sin(t*n.spd+n.phase);ctx.beginPath();ctx.arc(n.x,n.y,n.r*(0.8+0.4*pulse),0,Math.PI*2);ctx.fillStyle=P+(0.3+0.4*pulse)+')';ctx.fill();});requestAnimationFrame(frame);}
window.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;},{passive:true});window.addEventListener('resize',resize);resize();requestAnimationFrame(frame);}
if(window.innerWidth>768){if(window.requestIdleCallback){requestIdleCallback(initCanvas,{timeout:2000});}else{setTimeout(initCanvas,200);}}});