backend:
  name: github
  repo: TVU_J_GITHUB_PROFIL/NAZEV_REPOSITARE  # SEM NAPRAV TŮJ PROFIL/REPOSITÁŘ (např. janyskova/web)
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "hlavni_strana"
    label: "Hlavní stránka webu"
    files:
      - file: "index.html"
        label: "Úvodní texty (Hero)"
        name: "hero_sekce"
        fields:
          - { label: "Hlavní nadpis (H1)", name: "heading", widget: "string" }
          - { label: "Podnadpis (Popisný text)", name: "hero_text", widget: "text" }
