backend:
  name: github
  repo: gabrielajanyskova-sketch/janyskovadigital
  branch: main
  base_url: https://janyskovadigital.cz
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "hlavni_strana"
    label: "Hlavní stránka webu"
    files:
      - file: "index.html"
        label: "Úvodní texty (Hero)"
        name: "hero_sekce"
        fields:
          - { label: "Hlavní nadpis (H1)", name: "heading", widget: "string" }
          - { label: "Podnadpis (Popisný text)", name: "hero_text", widget: "text" }
