backend:
  name: github
  repo: TVOJE_JMÉNO_NA_GITHUBU/NÁZEV_REPOSITÁŘE # Sem napiš jak se jmenuješ na GitHubu/název projektu
  branch: main
  base_url: https://decap-cms-oauth.vercel.app # Bezplatná brána pro bezpečné přihlášení
  auth_endpoint: api/auth

media_folder: "images" # Sem se uloží fotky, které klient nahraje
public_folder: "/images"

collections:
  - name: "stranky"
    label: "Obsah webu"
    files:
      - file: "index.html" # Soubor, který chce klient upravovat
        label: "Hlavní stránka"
        name: "home"
        fields:
          - { label: "Hlavní velký nadpis", name: "heading", widget: "string" }
          - { label: "Popisný text v úvodu", name: "hero_text", widget: "text" }
